name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run lint
      - run: npm run test:coverage
      - name: Collect coverage
        uses: codecov/codecov-action@v2
        if: success()
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: true
